package finalproject;

import java.util.*;
import java.awt.*;
import java.io.*;
import javax.swing.*;
import java.lang.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Geometry helper can read previous calculations from a file for easy access.
 * The new calculations option will give choices on which shape and then ask for dimensions.
 * Shape objects are initialized to null until they are given values.
 * If dimensions are invalid, an exception is thrown.
 * @author aferris17
 */
public class NewJFrame extends javax.swing.JFrame {
    
    File f = new File("C:\\Users\\aferris17\\Documents\\Geometry.txt");
    //File f = new File ("Geometry.txt");
        
   
    Ellipse ell = null;
    Triangle tri = null;
    Rectangle rec = null;
    
    Cone cone = null;
    EllipticalCyl ellC = null;
    RectPrism RecP = null;
    Sphere sph = null;
    SquarePyr squP = null;
    
    String s;
    String selected;
    ArrayList<String> array = new ArrayList<String>();
    ArrayList<String> shapeArray = new ArrayList<String>(Arrays.asList("Circle","Rectangle", "Triangle","Square","Ellipse",
    "Rectangular Pyramid","Cone","Elliptical Cylinder","Rectangular Prism","Sphere"));
    

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        //shapes.setBackground(Color.yellow);
        
        OldCalc.setVisible(false);
        NewCalc.setVisible(false);
        
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        Area.setVisible(false);
        Perim.setVisible(false);
        Calc.setVisible(false);
        options.setVisible(false);
        jScrollPane1.setVisible(false);
        OldList.setVisible(false);
        jScrollPane2.setVisible(false);
        
        Circle.setVisible(false);
        Cone.setVisible(false);
        Ellipse.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        OldCalc = new javax.swing.JButton();
        NewCalc = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Area = new javax.swing.JLabel();
        Perim = new javax.swing.JLabel();
        Calc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        options = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        OldList = new javax.swing.JList();
        Cone = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        RectangularPrism = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        EllipticalCylinder = new javax.swing.JLabel();
        Sphere = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        Square = new javax.swing.JLabel();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        Circle = new javax.swing.JLabel();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        Ellipse = new javax.swing.JLabel();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        RectangularPyramid = new javax.swing.JLabel();
        jLayeredPane9 = new javax.swing.JLayeredPane();
        Triangle = new javax.swing.JLabel();
        Rectangle = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Geometry Helper");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        nameLabel.setText("Username:");

        OldCalc.setText("View my old Calculations");
        OldCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldCalcActionPerformed(evt);
            }
        });

        NewCalc.setText("Make new Calculation");
        NewCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCalcActionPerformed(evt);
            }
        });

        Area.setText("jLabel6");

        Perim.setText("jLabel6");

        Calc.setText("Calculate!");
        Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcActionPerformed(evt);
            }
        });

        options.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Circle", "Rectangle", "Triangle", "Square", "Ellipse", "Rectangular Pyramid", "Cone", "Elliptical Cylinder", "Rectangular Prism", "Sphere" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        options.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                optionsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(options);

        jLabel6.setText("   ");

        jLabel7.setText("    ");

        jLabel8.setText("    ");

        OldList.setModel(new DefaultListModel<String>(){
            public int getSize(){return array.size();}
            public String getElementAt(int i){return array.get(i);}
            public void addElement(String f){super.addElement(f);array.add(f);}
            public void add(int i, String f){super.add(i,f);array.add(i,f);}
        });
        jScrollPane2.setViewportView(OldList);

        Cone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Cone.gif"))); // NOI18N
        Cone.setText(" ");

        RectangularPrism.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/RectPrism.gif"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RectangularPrism)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RectangularPrism)
                .addContainerGap())
        );
        jLayeredPane1.setLayer(RectangularPrism, javax.swing.JLayeredPane.DEFAULT_LAYER);

        EllipticalCylinder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Elliptical Cylinder.png"))); // NOI18N

        Sphere.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Sph.jpg"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(EllipticalCylinder))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Sphere)
                .addGap(23, 23, 23))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane2Layout.createSequentialGroup()
                .addComponent(Sphere)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EllipticalCylinder)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(EllipticalCylinder, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane2.setLayer(Sphere, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );

        Square.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Square.png"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(Square)
                .addGap(209, 209, 209))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Square)
                .addContainerGap())
        );
        jLayeredPane4.setLayer(Square, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Circle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Circle.jpg"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Circle)
                .addContainerGap())
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Circle)
                .addContainerGap())
        );
        jLayeredPane5.setLayer(Circle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Ellipse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/ellipse.png"))); // NOI18N
        Ellipse.setText(" ");

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ellipse, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ellipse)
                .addContainerGap())
        );
        jLayeredPane6.setLayer(Ellipse, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 188, Short.MAX_VALUE)
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 190, Short.MAX_VALUE)
        );

        RectangularPyramid.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/RectPyramid.jpg"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RectangularPyramid)
                .addContainerGap())
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RectangularPyramid)
                .addContainerGap())
        );
        jLayeredPane8.setLayer(RectangularPyramid, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Triangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Triangle.gif"))); // NOI18N

        javax.swing.GroupLayout jLayeredPane9Layout = new javax.swing.GroupLayout(jLayeredPane9);
        jLayeredPane9.setLayout(jLayeredPane9Layout);
        jLayeredPane9Layout.setHorizontalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Triangle)
                .addContainerGap())
        );
        jLayeredPane9Layout.setVerticalGroup(
            jLayeredPane9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Triangle)
                .addContainerGap())
        );
        jLayeredPane9.setLayer(Triangle, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Rectangle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/newpackage/Rectangle.gif"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(144, 144, 144)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(OldCalc)
                                            .addComponent(NewCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nameLabel)
                                        .addGap(18, 18, 18)
                                        .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(SubmitButton))))
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(287, 287, 287)
                                .addComponent(Calc))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 827, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(Rectangle))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cone, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(72, 72, 72)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Perim)
                                    .addComponent(Area))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLayeredPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitButton)
                    .addComponent(nameLabel))
                .addGap(8, 8, 8)
                .addComponent(OldCalc)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(NewCalc))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Calc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8)
                                    .addComponent(Perim))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(122, 122, 122))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel7))
                                            .addComponent(Area))
                                        .addGap(18, 18, 18)
                                        .addComponent(Cone))
                                    .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel3)
                                                        .addGap(126, 126, 126)
                                                        .addComponent(jLabel4)
                                                        .addGap(78, 78, 78)
                                                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(Rectangle)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLayeredPane5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLayeredPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLayeredPane9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        s = Username.getText();
        
        //changePanel(shapes);

        
        Username.setVisible(false);
        SubmitButton.setVisible(false);
        nameLabel.setText("");
        
        OldCalc.setVisible(true);
        NewCalc.setVisible(true);
        
        

    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void NewCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCalcActionPerformed
        OldCalc.setVisible(false);
        NewCalc.setVisible(false);
        
        options.setVisible(true);
        jScrollPane1.setVisible(true);
    }//GEN-LAST:event_NewCalcActionPerformed
/**/
    private void CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcActionPerformed
        Area.setVisible(true);
        Perim.setVisible(true);
        
        String p, a;
        
        if (selected.equals("Ellipse")) {

            try {
                ell = new Ellipse(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField2.getText()));

            } catch (MyException e) {
                Area.setText("Something went wrong");
                Perim.setText("");
            };
            p=String.format("Perimeter: %.2f",ell.getPerimeter());
            a=String.format("Area: %.2f", ell.getArea());
            Perim.setText(p);
            Area.setText(a);
        }
        else if (selected.equals("Triangle")) {
            try{
            tri = new Triangle (Integer.parseInt(jTextField1.getText()),
                    Integer.parseInt(jTextField2.getText()),
                    Integer.parseInt(jTextField3.getText()));
            
                }catch (MyException e){
                   Area.setText("Something went wrong");
                Perim.setText("");};
            p=String.format("Perimeter: %.2f",tri.getPerimeter());
            a=String.format("Area: %.2f", tri.getArea());
            Perim.setText(p);
            Area.setText(a);
        }
        else if (selected.equals("Rectangle")) {
            try {
                rec = new Rectangle(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField2.getText()));

            } catch (MyException e) {
             Area.setText("Something went wrong");
                Perim.setText("");};
            p=String.format("Perimeter: %.2f",rec.getPerimeter());
            a=String.format("Area: %.2f", rec.getArea());
            Perim.setText(p);
            Area.setText(a);
        }
        else if (selected.equals("Square Pyramid")) {
            try{
            squP = new SquarePyr (Integer.parseInt(jTextField1.getText()),
                    Integer.parseInt(jTextField2.getText()),
                    Integer.parseInt(jTextField3.getText()));
            
                }catch (MyException e){ Area.setText("Something went wrong");
                Perim.setText("");};
            p=String.format("Perimeter: %.2f",squP.getSurfaceArea());
            a=String.format("Area: %.2f", squP.getVolume());
            Perim.setText(p);
            Area.setText(a);
        }
        else if (selected.equals("Cone")) {
            try{
            cone = new Cone (Integer.parseInt(jTextField1.getText()),
                    Integer.parseInt(jTextField2.getText()));
            
                }catch (MyException e){Area.setText("Something went wrong");
                Perim.setText("");};
            p=String.format("Perimeter: %.2f",cone.getSurfaceArea());
            a=String.format("Area: %.2f", cone.getVolume());
            Perim.setText(p);
            Area.setText(a);
        }
        else if (selected.equals("Elliptical Cylinder")) {
            try{
            ellC = new EllipticalCyl (Integer.parseInt(jTextField1.getText()),
                    Integer.parseInt(jTextField2.getText()),
                    Integer.parseInt(jTextField3.getText()));
            
                }catch (MyException e){Area.setText("Something went wrong");
                Perim.setText("");};
            p=String.format("Perimeter: %.2f",ellC.getSurfaceArea());
            a=String.format("Area: %.2f", ellC.getVolume());
            Perim.setText(p);
            Area.setText(a);
        }
        else if (selected.equals("Rectangular Prism")) {
            try{
            RecP = new RectPrism (Integer.parseInt(jTextField1.getText()),
                    Integer.parseInt(jTextField2.getText()),
                    Integer.parseInt(jTextField3.getText()));
            
                }catch (MyException e){Area.setText("Something went wrong");
                Perim.setText("");};
            p=String.format("Perimeter: %.2f",RecP.getSurfaceArea());
            a=String.format("Area: %.2f", RecP.getVolume());
            Perim.setText(p);
            Area.setText(a);
        }
        else if (selected.equals("Sphere")) {
            try{
            sph = new Sphere (Integer.parseInt(jTextField1.getText()));
            
                }catch (MyException e){Area.setText("Something went wrong");
                Perim.setText("");};
            p=String.format("Perimeter: %.2f",sph.getSurfaceArea());
            a=String.format("Area: %.2f", sph.getVolume());
            Perim.setText(p);
            Area.setText(a);
        } 
        else if (selected.equals("Circle")) {
            try{
            ell = new Ellipse (Integer.parseInt(jTextField1.getText()), 
                    Integer.parseInt(jTextField1.getText()));
            
                }catch (MyException e){Area.setText("Something went wrong");
                Perim.setText("");
            };
            p=String.format("Perimeter: %.2f",ell.getPerimeter());
            a=String.format("Area: %.2f", ell.getArea());
            Perim.setText(p);
            Area.setText(a);
        } 
        else if (selected.equals("Square")) {
            try {
                rec = new Rectangle(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField1.getText()));

            } catch (MyException e) {
            };
            Perim.setText(Double.toString(rec.getPerimeter()));
            Area.setText(Double.toString(rec.getArea()));
        }
        else {
            Perim.setText("No shape was initialized");
            Area.setText("");
        }
        
        if (!f.exists())
            try {
                f.createNewFile();
        } catch (IOException ex) {
            Logger.getLogger(NewJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        BufferedWriter wrtr = null;

        try {
            wrtr = new BufferedWriter(new FileWriter(f));
            String line = String.format("%s \t %s %s %s", 
                    s,selected, Perim.getText(),Area.getText());
            wrtr.write(line);
            wrtr.newLine();
            wrtr.close();
        }
        catch (Exception ex){
            Perim.setText("Did not write to file");
            Area.setText("");
        }
            
        
    }//GEN-LAST:event_CalcActionPerformed
/**/
    private void OldCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldCalcActionPerformed

        OldList.setVisible(true);
        jScrollPane2.setVisible(true);
        
        BufferedReader rdr = null;

        try {
            rdr = new BufferedReader(new FileReader(f));
            String line;
            while ((line = rdr.readLine()) != null) {
                
                String[] str = line.split("[\t]+");
                String username=str[0];
                String entry = str[1];
                if (username.equals(Username.getText())){
                    ((DefaultListModel) OldList.getModel()).addElement(entry);
                }
            }
            rdr.close();

        } catch (Exception ex) {
            ex.printStackTrace();
            Area.setText("Something went wrong. Sorry!");
        }
    }//GEN-LAST:event_OldCalcActionPerformed
/**/
    private void optionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_optionsValueChanged
      
        if (options.getSelectedIndex() != -1) {
            selected = shapeArray.get(options.getSelectedIndex());
            System.out.println(selected);
            
        }
        if (selected.equals("Circle")) {
            jTextField1.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("Radius:");
        } else if (selected.equals("Rectangle")) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("Length:");
            jLabel7.setText("Width:");
        } else if (selected.equals("Triangle")) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("Side 1:");
            jLabel7.setText("Side 2:");
            jLabel8.setText("Side 4:");
        } else if (selected.equals("Square")) {
            jTextField1.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("Side:");
        } else if (selected.equals("Ellipse")) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("radius 1:");
            jLabel7.setText("radius 2:");
        } else if (selected.equals("Rectangular Pyramid")) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("Length:");
            jLabel7.setText("Width:");
            jLabel8.setText("Height:");
        } else if (selected.equals("Cone")) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("Radius:");
            jLabel7.setText("Height:");
        } else if (selected.equals("Elliptical Cylinder")) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("Radius 1:");
            jLabel7.setText("Radius 2:");
            jLabel8.setText("Height:");
        } else if (selected.equals("Rectangular Prism")) {
            jTextField1.setVisible(true);
            jTextField2.setVisible(true);
            jTextField3.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("Length:");
            jLabel7.setText("Width:");
            jLabel8.setText("Height:");
        } else if (selected.equals("Sphere")) {
            jTextField1.setVisible(true);
            Calc.setVisible(true);
            jLabel6.setText("Radius:");
        }
        
    }//GEN-LAST:event_optionsValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Area;
    private javax.swing.JButton Calc;
    private javax.swing.JLabel Circle;
    private javax.swing.JLabel Cone;
    private javax.swing.JLabel Ellipse;
    private javax.swing.JLabel EllipticalCylinder;
    private javax.swing.JButton NewCalc;
    private javax.swing.JButton OldCalc;
    private javax.swing.JList OldList;
    private javax.swing.JLabel Perim;
    private javax.swing.JLabel Rectangle;
    private javax.swing.JLabel RectangularPrism;
    private javax.swing.JLabel RectangularPyramid;
    private javax.swing.JLabel Sphere;
    private javax.swing.JLabel Square;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JLabel Triangle;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JLayeredPane jLayeredPane9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JList options;
    // End of variables declaration//GEN-END:variables
}
