package finalproject;

import java.util.*;
import java.awt.*;
import java.io.*;
import javax.swing.*;
import java.lang.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * Geometry helper can read previous calculations from a file for easy access.
 * The new calculations option will give choices on which shape and then ask for dimensions.
 * Shape objects are initialized to null until they are given values.
 * If dimensions are invalid, an exception is thrown.
 * @author aferris17
 */
public class NewJFrame extends javax.swing.JFrame {
    
    //File f = new File("C:\\Users\\aferris17\\Documents\\Geometry.txt");
    
    File f = new File ("Geometry.txt");
        
   
    Ellipse ell = null;
    Triangle tri = null;
    Rectangle rec = null;
    
    Cone cone = null;
    EllipticalCyl ellC = null;
    RectPrism RecP = null;
    Sphere sph = null;
    SquarePyr squP = null;
    
    String s;
    String selected;
    ArrayList<String> array = new ArrayList<String>();
    ArrayList<String> shapeArray = new ArrayList<String>(Arrays.asList("Circle","Rectangle", "Triangle","Square","Ellipse",
    "Rectangular Pyramid","Cone","Elliptical Cylinder","Rectangular Prism","Sphere"));
    Visibility visibility;

    /**
     * Creates new form NewJFrame
     * Sets many components to invisible, to be visible later.
     */
    public NewJFrame() {
        this.visibility = new Visibility();
        initComponents();
        visibility.Invisible(OldCalc,NewCalc,jTextField1,jTextField2,
                jTextField3,Area,Perim,Calc,options,jScrollPane1,
                OldList,jScrollPane2,jLabel9,listLabel,Logout,BackButton);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Calc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        options = new javax.swing.JList();
        jLabel9 = new javax.swing.JLabel();
        LoginPane = new javax.swing.JLayeredPane();
        jPanel3 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        Username = new javax.swing.JTextField();
        SubmitButton = new javax.swing.JButton();
        Choice = new javax.swing.JPanel();
        OldCalc = new javax.swing.JButton();
        NewCalc = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        OldList = new javax.swing.JList();
        Results = new javax.swing.JLayeredPane();
        Area = new javax.swing.JLabel();
        Perim = new javax.swing.JLabel();
        listLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();
        Logout = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Geometry Helper");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Calc.setText("Calculate!");
        Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcActionPerformed(evt);
            }
        });

        options.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Circle", "Rectangle", "Triangle", "Square", "Ellipse", "Rectangular Pyramid", "Cone", "Elliptical Cylinder", "Rectangular Prism", "Sphere" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        options.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                optionsValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(options);

        jLabel9.setText(" ");

        nameLabel.setText("Username:");

        SubmitButton.setText("Submit");
        SubmitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SubmitButton)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SubmitButton)
                    .addComponent(nameLabel)))
        );

        javax.swing.GroupLayout LoginPaneLayout = new javax.swing.GroupLayout(LoginPane);
        LoginPane.setLayout(LoginPaneLayout);
        LoginPaneLayout.setHorizontalGroup(
            LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LoginPaneLayout.setVerticalGroup(
            LoginPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginPaneLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        LoginPane.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        OldCalc.setText("View my old Calculations");
        OldCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OldCalcActionPerformed(evt);
            }
        });

        NewCalc.setText("Make new Calculation");
        NewCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChoiceLayout = new javax.swing.GroupLayout(Choice);
        Choice.setLayout(ChoiceLayout);
        ChoiceLayout.setHorizontalGroup(
            ChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OldCalc))
                .addContainerGap())
        );
        ChoiceLayout.setVerticalGroup(
            ChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(OldCalc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NewCalc)
                .addContainerGap())
        );

        OldList.setModel(new DefaultListModel<String>(){
            public int getSize(){return array.size();}
            public String getElementAt(int i){return array.get(i);}
            public void addElement(String f){super.addElement(f);array.add(f);}
            public void add(int i, String f){super.add(i,f);array.add(i,f);}
            public void clear(){super.clear();array.clear();}

        });
        jScrollPane2.setViewportView(OldList);

        Area.setText("jLabel6");

        Perim.setText("jLabel6");

        javax.swing.GroupLayout ResultsLayout = new javax.swing.GroupLayout(Results);
        Results.setLayout(ResultsLayout);
        ResultsLayout.setHorizontalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Perim)
                    .addComponent(Area))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        ResultsLayout.setVerticalGroup(
            ResultsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(Area)
                .addGap(18, 18, 18)
                .addComponent(Perim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Results.setLayer(Area, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Results.setLayer(Perim, javax.swing.JLayeredPane.DEFAULT_LAYER);

        listLabel.setText("jLabel10");

        BackButton.setText("Go Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        Logout.setText("Logout");
        Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutActionPerformed(evt);
            }
        });

        jLabel6.setText("   ");

        jLabel7.setText("    ");

        jLabel8.setText("    ");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(502, 502, 502)
                        .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(LoginPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(listLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(242, 242, 242))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(112, 112, 112)
                            .addComponent(jLabel9))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(340, 340, 340)
                            .addComponent(Calc))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Logout)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BackButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(113, 113, 113)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Choice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Logout)
                    .addComponent(BackButton))
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LoginPane, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(listLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Choice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)))))
                .addComponent(Calc)
                .addGap(118, 118, 118)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9))
                .addGap(118, 118, 118)
                .addComponent(jLabel4)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    /*
    *Calculation button initializes the shape and outputs the values in labels
    */
    private void CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcActionPerformed
        visibility.Visible(Area, Perim);
        String p, a;

        if (selected.equals("Ellipse")) {

            try {
                ell = new Ellipse(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField2.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions must be >0.");
                Perim.setText("");
            };
            p = String.format("Perimeter: %.2f", ell.getPerimeter());
            a = String.format("Area: %.2f", ell.getArea());
            Perim.setText(p);
            Area.setText(a);
        } else if (selected.equals("Triangle")) {
            try {
                tri = new Triangle(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField2.getText()),
                        Integer.parseInt(jTextField3.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions are not valid.");
                Perim.setText("");
            };
            p = String.format("Perimeter: %.2f", tri.getPerimeter());
            a = String.format("Area: %.2f", tri.getArea());
            Perim.setText(p);
            Area.setText(a);
        } else if (selected.equals("Rectangle")) {
            try {
                rec = new Rectangle(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField2.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions must be >0.");
                Perim.setText("");
            };
            p = String.format("Perimeter: %.2f", rec.getPerimeter());
            a = String.format("Area: %.2f", rec.getArea());
            Perim.setText(p);
            Area.setText(a);
        } else if (selected.equals("Rectangular Pyramid")) {
            try {
                squP = new SquarePyr(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField2.getText()),
                        Integer.parseInt(jTextField3.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions must be >0.");
                Perim.setText("");
            };
            p = String.format("Surface Area: %.2f", squP.getSurfaceArea());
            a = String.format("Volume: %.2f", squP.getVolume());
            Perim.setText(p);
            Area.setText(a);
        } else if (selected.equals("Cone")) {
            try {
                cone = new Cone(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField2.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions must be >0.");
                Perim.setText("");
            };
            p = String.format("Surface Area: %.2f", cone.getSurfaceArea());
            a = String.format("Volume: %.2f", cone.getVolume());
            Perim.setText(p);
            Area.setText(a);
        } else if (selected.equals("Elliptical Cylinder")) {
            try {
                ellC = new EllipticalCyl(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField2.getText()),
                        Integer.parseInt(jTextField3.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions must be >0.");
                Perim.setText("");
            };
            p = String.format("Surface Area: %.2f", ellC.getSurfaceArea());
            a = String.format("Volume: %.2f", ellC.getVolume());
            Perim.setText(p);
            Area.setText(a);
        } else if (selected.equals("Rectangular Prism")) {
            try {
                RecP = new RectPrism(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField2.getText()),
                        Integer.parseInt(jTextField3.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions must be >0.");
                Perim.setText("");
            };
            p = String.format("Surface Area: %.2f", RecP.getSurfaceArea());
            a = String.format("Volume: %.2f", RecP.getVolume());
            Perim.setText(p);
            Area.setText(a);
        } else if (selected.equals("Sphere")) {
            try {
                sph = new Sphere(Integer.parseInt(jTextField1.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions must be >0.");
                Perim.setText("");
            };
            p = String.format("Surface Area: %.2f", sph.getSurfaceArea());
            a = String.format("Volume: %.2f", sph.getVolume());
            Perim.setText(p);
            Area.setText(a);
        } else if (selected.equals("Circle")) {
            try {
                ell = new Ellipse(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField1.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions must be >0.");
                Perim.setText("");
            };
            p = String.format("Perimeter: %.2f", ell.getPerimeter());
            a = String.format("Area: %.2f", ell.getArea());
            Perim.setText(p);
            Area.setText(a);
        } else if (selected.equals("Square")) {
            try {
                rec = new Rectangle(Integer.parseInt(jTextField1.getText()),
                        Integer.parseInt(jTextField1.getText()));

            } catch (MyException e) {
                Area.setText("Dimensions must be >0.");
                Perim.setText("");
            };
            p = String.format("Perimeter: %.2f", rec.getPerimeter());
            a = String.format("Area: %.2f", rec.getArea());
            Perim.setText(p);
            Area.setText(a);
        } else {
            Perim.setText("No shape was initialized");
            Area.setText("");
        }

        
        BufferedWriter wrtr = null;

        try {
            wrtr = new BufferedWriter(new FileWriter(f,true));
            String line = String.format("%s\t%s, %s, %s",
                    s, selected,
                    Perim.getText(), Area.getText());
            wrtr.write(line);
            wrtr.newLine();
            wrtr.close();
        } catch (Exception ex) {
            Perim.setText("Did not write to file");
            Area.setText("");
        }

    }//GEN-LAST:event_CalcActionPerformed

/**/
    private void optionsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_optionsValueChanged
      Images images = new Images();
        if (options.getSelectedIndex() != -1) {
            selected = shapeArray.get(options.getSelectedIndex());
        }
        if (selected.equals("Circle")) {
            jLabel9.setIcon(images.setImage("Circle"));
            visibility.Visible(jTextField1,Calc,jLabel9,jLabel6);
            visibility.Invisible(jTextField2,jTextField3,jLabel7,jLabel8);
            jLabel6.setText("Radius:");
        } else if (selected.equals("Rectangle")) {
            jLabel9.setIcon(images.setImage("Rectangle"));
            visibility.Visible(jTextField1,jTextField2,Calc,jLabel9,jLabel6,jLabel7);
            visibility.Invisible(jTextField3,jLabel8);
            jLabel6.setText("Length:");
            jLabel7.setText("Width:");
        } else if (selected.equals("Triangle")) {
            jLabel9.setIcon(images.setImage("Triangle"));
            visibility.Visible(jTextField1,jTextField2,jTextField3,Calc,jLabel9,jLabel6,jLabel7,jLabel8);
            jLabel6.setText("Side 1:");
            jLabel7.setText("Side 2:");
            jLabel8.setText("Side 4:");
        } else if (selected.equals("Square")) {
            jLabel9.setIcon(images.setImage("Square"));
            visibility.Visible(jTextField1,Calc,jLabel6,jLabel9);
            visibility.Invisible(jTextField2,jTextField3,jLabel7,jLabel8);
            jLabel6.setText("Side:");
        } else if (selected.equals("Ellipse")) {
            jLabel9.setIcon(images.setImage("Ellipse"));
            visibility.Visible(jTextField1,jTextField2,Calc,jLabel9,jLabel7,jLabel6);
            visibility.Invisible(jTextField3,jLabel8);
            jLabel6.setText("radius 1:");
            jLabel7.setText("radius 2:");
        } else if (selected.equals("Rectangular Pyramid")) {
            jLabel9.setIcon(images.setImage("Rectangular Pyramid"));
            visibility.Visible(jTextField1,jTextField2,jTextField3,Calc,jLabel9,jLabel6,jLabel7,jLabel8);
            jLabel6.setText("Length:");
            jLabel7.setText("Width:");
            jLabel8.setText("Height:");
        } else if (selected.equals("Cone")) {
            jLabel9.setIcon(images.setImage("Cone"));
            visibility.Visible(jTextField1,jTextField2,Calc,jLabel9,jLabel6,jLabel7);
            visibility.Invisible(jTextField3,jLabel8);
            jLabel6.setText("Radius:");
            jLabel7.setText("Height:");
        } else if (selected.equals("Elliptical Cylinder")) {
            jLabel9.setIcon(images.setImage("Elliptical Cylinder"));
            visibility.Visible(jTextField1,jTextField2,jTextField3,Calc,jLabel9,jLabel6,jLabel7,jLabel8);
            jLabel6.setText("Radius 1:");
            jLabel7.setText("Radius 2:");
            jLabel8.setText("Height:");
        } else if (selected.equals("Rectangular Prism")) {
            jLabel9.setIcon(images.setImage("Rectangular Prism"));
            visibility.Visible(jTextField1,jTextField2,jTextField3,Calc,jLabel9,jLabel6,jLabel7,jLabel8);
            jLabel6.setText("Length:");
            jLabel7.setText("Width:");
            jLabel8.setText("Height:");
        } else if (selected.equals("Sphere")) {
            jLabel9.setIcon(images.setImage("Sphere"));
            visibility.Visible(jTextField1,Calc,jLabel9,jLabel6);
            visibility.Invisible(jTextField2,jTextField3,jLabel7,jLabel8);
            jLabel6.setText("Radius:");
        }
        
    }//GEN-LAST:event_optionsValueChanged

    private void NewCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewCalcActionPerformed
        visibility.Invisible(OldCalc,NewCalc);
        visibility.Visible(options,jScrollPane1,BackButton);

    }//GEN-LAST:event_NewCalcActionPerformed

    private void SubmitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitButtonActionPerformed
        s = Username.getText();
        if (s.equals("")) {
            visibility.Visible(listLabel);
            listLabel.setText("You must enter a username");
        } else {
            visibility.Invisible(LoginPane,listLabel);
            visibility.Visible(OldCalc, NewCalc, Logout);
        }
    }//GEN-LAST:event_SubmitButtonActionPerformed

    private void OldCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OldCalcActionPerformed
        ((DefaultListModel) OldList.getModel()).clear();
        visibility.Invisible(OldCalc,NewCalc);
        visibility.Visible(OldList,jScrollPane2,BackButton,listLabel);
        BufferedReader rdr = null;
        ArrayList <String> calculations = new ArrayList<String>();
        //calculations = null;
        
        
        try{
            rdr=new BufferedReader(new FileReader(f));
            String line;
           while ((line = rdr.readLine()) != null) {

                String[] str = line.split("[\t]+");
                String username = str[0];
                String entry = str[1];
                if(s.equals(username)){
                    calculations.add(entry);
                }
            }rdr.close();
        } catch (Exception ex) {
            ex.printStackTrace();
            listLabel.setText("Something went wrong. Sorry!");
        }
        for (int i = 0; i < calculations.size(); i++) {
            ((DefaultListModel) OldList.getModel()).addElement(calculations.get(i));
        }
        if (((DefaultListModel) OldList.getModel()).getSize() == 0) {
            listLabel.setText("We didn't find any old calculatinos.");
        } else {
            listLabel.setText("Your old calculations:");
        }
    }//GEN-LAST:event_OldCalcActionPerformed

    private void LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutActionPerformed
        visibility.Invisible(OldCalc,NewCalc,jTextField1,jTextField2,
                jTextField3,Area,Perim,Calc,options,jScrollPane1,
                OldList,jScrollPane2,jLabel9,listLabel,Logout,BackButton,jLabel6, jLabel7,jLabel8);
        
        visibility.Visible(LoginPane);
    }//GEN-LAST:event_LogoutActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        visibility.Invisible(OldCalc,NewCalc,jTextField1,jTextField2,
                jTextField3,Area,Perim,Calc,options,jScrollPane1,
                OldList,jScrollPane2,jLabel9,listLabel,Logout,BackButton,LoginPane,jLabel6, jLabel7,jLabel8);
        visibility.Visible(OldCalc,NewCalc,Logout);
    }//GEN-LAST:event_BackButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Area;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton Calc;
    private javax.swing.JPanel Choice;
    private javax.swing.JLayeredPane LoginPane;
    private javax.swing.JButton Logout;
    private javax.swing.JButton NewCalc;
    private javax.swing.JButton OldCalc;
    private javax.swing.JList OldList;
    private javax.swing.JLabel Perim;
    private javax.swing.JLayeredPane Results;
    private javax.swing.JButton SubmitButton;
    private javax.swing.JTextField Username;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel listLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JList options;
    // End of variables declaration//GEN-END:variables
}
