/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package exam1;
import java.util.*;
import java.io.*;

/**
 * UnderOver allows user to access their balance and place new bets.
 * The dice roll results in a value either under, over, or equal to 7
 * and rewards based on the user's bet.
 * The game does not yet have a feature for storing previous balances, but 
 * this feature is in progress.
 * @author aferris17
 */
public class UnderOver extends javax.swing.JFrame {
    HashMap <String, User> users = new HashMap<String, User>();
    Random rand = new Random();
    
    File file = new File("C:\\Users\\aferris17\\Documents\\new1.txt");
    File fcopy = new File("C:\\Users\\aferris17\\Documents\\new2.txt");


    /**
     * Creates new form UnderOver
     */
    public UnderOver() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Login = new javax.swing.JButton();
        Greet = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Bet = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Warn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Login Name:");

        Login.setText("OK");
        Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginActionPerformed(evt);
            }
        });

        Greet.setText("Welcome!");

        jLabel3.setText("How much would you like to bet?");

        jButton2.setText("Under 7");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Over 7");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Exactly 7");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel2.setText("Place a bet on whether the result of a two-dice roll will be under, over, or exactly 7");

        jLabel4.setFont(new java.awt.Font("Perpetua", 0, 36)); // NOI18N
        jLabel4.setText("Under Over");

        jLabel5.setText("To place your bet, please select an option below:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109)
                .addComponent(Login)
                .addGap(261, 261, 261))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(82, 82, 82)
                .addComponent(jButton4)
                .addGap(252, 252, 252))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(50, 50, 50)
                                .addComponent(Bet, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Warn)
                            .addComponent(Greet))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login)
                    .addComponent(jLabel1)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Greet)
                .addGap(101, 101, 101)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Bet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(Warn)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginActionPerformed


        String f = Name.getText();
        String g = null;

 /*       try {
            BufferedReader rdr = new BufferedReader(new FileReader(file));
            String line_name;
            String line_bal;
            while ((rdr.readLine()) != null) {
                line_name = rdr.readLine();
                line_bal = rdr.readLine();
                int bal = Integer.parseInt(line_bal);
                users.put(line_name, new User(line_name, bal));
            }
            rdr.close();
        } catch (Exception ex) {
            Greet.setText("Something went wrong. Sorry!");
        }
  */      

        if (users.containsKey(f)) {
            User u = users.get(f);
            g = String.format("Welcome %s! Your current balance is $%d. ", f,
                    u.getBalance());
            Greet.setText(g);

        } else if (!(users.containsKey(f))) {
            User u = new User(f);
            g = String.format("Welome %s! Your current balance is $500.", f);
            users.put(f, u);
            Greet.setText(g);

  /*         try {
                BufferedReader rdr = new BufferedReader(new FileReader(file));
                BufferedWriter wrtr = new BufferedWriter(new FileWriter(fcopy));
                String line;
                for (int i=0;i<users.size();i++) {
                    User curr = users.get(i);
                    String s = curr.getName();
                    User match = users.get(curr);
                    
                    wrtr.write(curr);
                    wrtr.newLine();
                }
                rdr.close();
                wrtr.close();
            } catch (Exception ex) {
                Greet.setText("Something went wrong. Sorry!");
            }
*/
        }

        
        
        
        
        
    }//GEN-LAST:event_LoginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        int bet = Integer.parseInt(Bet.getText());
        int x;
        String t = null;
        String f = null;
        User u = users.get(Name.getText());
        
        try {
            u.placeBet(bet);
            x = rand.nextInt(12)+1;
            if (x<7){
                t = String.format ("Result: %d  Congratulations! You won $%d", x, bet);
                Warn.setText(t);
                u.setBalance(bet);
            }
            else if (x>7){
                t = String.format("Result: %d  Terribly sorry, you lost.$%d", x, bet);
                Warn.setText(t);
                u.setBalance(-(bet));
            }
        }catch(MyException e){
            Warn.setText("Your bet is too high!");
        }
        f = String.format("Your current balance is $%d. ", u.getBalance());
        Greet.setText(f);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int bet = Integer.parseInt(Bet.getText());
        int x;
        String t = null;
        String f = null;
        User u = users.get(Name.getText());
        
        try {
            u.placeBet(bet);
            x = rand.nextInt(12);
            if (x>7){
                t = String.format ("Result: %d  Congratulations! You won $%d", x, bet);
                Warn.setText(t);
                u.setBalance(bet);
            }
            else if (x<7){
                t = String.format("Result: %d  Terribly sorry, you lost.$%d", x, bet);
                Warn.setText(t);
                u.setBalance(-(bet));
            }
        }catch(MyException e){
            Warn.setText("Your bet is too high!");
        }
        f = String.format("Your current balance is $%d. ", u.getBalance());
        Greet.setText(f);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int bet = Integer.parseInt(Bet.getText());
        int pay = 4*bet;
        int x;
        String t = null;
        String f = null;
        User u = users.get(Name.getText());
        
        try {
            u.placeBet(bet);
            x = rand.nextInt(12);
            if (x==7){
                t = String.format ("Result: %d  Congratulations! Luck is on your side. You won $%d", x, pay);
                Warn.setText(t);
                u.setBalance(bet);
            }
            else if (x!=7){
                t = String.format("Result: %d  Terribly sorry, you lost.$%d", x, bet);
                Warn.setText(t);
                u.setBalance(-(bet));
            }
        }catch(MyException e){
            Warn.setText("Your bet is too high!");
        }
        f = String.format("Your current balance is $%d. ", u.getBalance());
        Greet.setText(f);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UnderOver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UnderOver().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Bet;
    private javax.swing.JLabel Greet;
    private javax.swing.JButton Login;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel Warn;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
